// scripts/probar-loop.ts
//
// Loop without payments: question -> answer with citations -> verified citations.
// Connects ask.ts (Citations API) with verify.ts (the guard).
// Run with:  npx tsx scripts/probar-loop.ts

import "dotenv/config";
import { ask } from "../agent/ask";
import { verifyCitations, type Corpus } from "../agent/verify";

// Hardcoded corpus for the smoke test (a fictional open access paper).
const corpus: Corpus = {
  "paper-001": `Open Access and Author Compensation

Open access accelerates scientific progress by removing paywalls that restrict
who can read research. Studies show that openly available papers are cited more
often than those behind subscription barriers.

Authors, however, rarely receive direct compensation for citations. The economic
value generated by a citation flows to publishers and indexing services, not to
the researchers who produced the work.`,
};

const question = "Why does open access not benefit authors economically?";

const answer = await ask(question, corpus);
const verified = verifyCitations(answer.citations, corpus);

console.log("QUESTION");
console.log(answer.question + "\n");

console.log("ANSWER");
console.log(answer.text + "\n");

console.log(`VERIFIED CITATIONS (${verified.length}/${answer.citations.length})`);
for (const cita of verified) {
  console.log(`  [${cita.paperId}] "${cita.citedText}"`);
}
