// scripts/probar-loop.ts
//
// Loop sin pagos: pregunta -> respuesta con citas -> citas verificadas.
// Conecta ask.ts (Citations API) con verify.ts (el guard).
// Correr con:  npx tsx scripts/probar-loop.ts

import "dotenv/config";
import { ask } from "../agent/ask";
import { verifyCitations, type Corpus } from "../agent/verify";

// Corpus hardcodeado para el smoke test (un paper open access ficticio).
const corpus: Corpus = {
  "paper-001": `Open Access and Author Compensation

Open access accelerates scientific progress by removing paywalls that restrict
who can read research. Studies show that openly available papers are cited more
often than those behind subscription barriers.

Authors, however, rarely receive direct compensation for citations. The economic
value generated by a citation flows to publishers and indexing services, not to
the researchers who produced the work.`,
};

const question = "Why does open access not benefit authors economically?";

const answer = await ask(question, corpus);
const verified = verifyCitations(answer.citations, corpus);

console.log("PREGUNTA");
console.log(answer.question + "\n");

console.log("RESPUESTA");
console.log(answer.text + "\n");

console.log(`CITAS VERIFICADAS (${verified.length}/${answer.citations.length})`);
for (const cita of verified) {
  console.log(`  [${cita.paperId}] "${cita.citedText}"`);
}
